export const GET_FAMILYRELATIONSHIP = "GET_FAMILYRELATIONSHIP";
export const GET_FAMILYRELATIONSHIP_SUCCESS = "GET_FAMILYRELATIONSHIP_SUCCESS";
export const GET_FAMILYRELATIONSHIP_FAIL = "GET_FAMILYRELATIONSHIP_FAIL";

export const CREATE_FAMILYRELATIONSHIP = "CREATE_FAMILYRELATIONSHIP";
export const CREATE_FAMILYRELATIONSHIP_SUCCESS =
  "CREATE_FAMILYRELATIONSHIP_SUCCESS";
export const CREATE_FAMILYRELATIONSHIP_FAIL = "CREATE_FAMILYRELATIONSHIP_FAIL";

export const UPDATE_FAMILYRELATIONSHIP = "UPDATE_FAMILYRELATIONSHIP";
export const UPDATE_FAMILYRELATIONSHIP_SUCCESS =
  "UPDATE_FAMILYRELATIONSHIP_SUCCESS";
export const UPDATE_FAMILYRELATIONSHIP_FAIL = "UPDATE_FAMILYRELATIONSHIP_FAIL";

export const DELETE_FAMILYRELATIONSHIP = "DELETE_FAMILYRELATIONSHIP";
export const DELETE_FAMILYRELATIONSHIP_SUCCESS =
  "DELETE_FAMILYRELATIONSHIP_SUCCESS";
export const DELETE_FAMILYRELATIONSHIP_FAIL = "DELETE_FAMILYRELATIONSHIP_FAIL";
