export const GET_ALL_PROCESS = "GET_PROCESS";
export const GET_ALL_PROCESS_SUCCESS = "GET_PROCESS_SUCCESS";
export const GET_ALL_PROCESS_FAIL = "GET_PROCESS_FAIL";

export const CREATE_PROCESS = "CREATE_PROCESS";
export const CREATE_PROCESS_SUCCESS = "CREATE_PROCESS_SUCCESS";
export const CREATE_PROCESS_FAIL = "CREATE_PROCESS_FAIL";

export const UPDATE_PROCESS = "UPDATE_PROCESS";
export const UPDATE_PROCESS_SUCCESS = "UPDATE_PROCESS_SUCCESS";
export const UPDATE_PROCESS_FAIL = "UPDATE_PROCESS_FAIL";

export const DELETE_PROCESS = "DELETE_PROCESS";
export const DELETE_PROCESS_SUCCESS = "DELETE_PROCESS_SUCCESS";
export const DELETE_PROCESS_FAIL = "DELETE_PROCESS_FAIL";
