export const GET_ALL_PROPOSAL = "GET_PROPOSAL";
export const GET_ALL_PROPOSAL_SUCCESS = "GET_PROPOSAL_SUCCESS";
export const GET_ALL_PROPOSAL_FAIL = "GET_PROPOSAL_FAIL";

export const CREATE_PROPOSAL = "CREATE_PROPOSAL";
export const CREATE_PROPOSAL_SUCCESS = "CREATE_PROPOSAL_SUCCESS";
export const CREATE_PROPOSAL_FAIL = "CREATE_PROPOSAL_FAIL";

export const UPDATE_PROPOSAL = "UPDATE_PROPOSAL";
export const UPDATE_PROPOSAL_SUCCESS = "UPDATE_PROPOSAL_SUCCESS";
export const UPDATE_PROPOSAL_FAIL = "UPDATE_PROPOSAL_FAIL";

export const DELETE_PROPOSAL = "DELETE_PROPOSAL";
export const DELETE_PROPOSAL_SUCCESS = "DELETE_PROPOSAL_SUCCESS";
export const DELETE_PROPOSAL_FAIL = "DELETE_PROPOSAL_FAIL";
