export const GET_ALL_SALARY_INCREASE = "GET_SALARY_INCREASE";
export const GET_ALL_SALARY_INCREASE_SUCCESS = "GET_SALARY_INCREASE_SUCCESS";
export const GET_ALL_SALARY_INCREASE_FAIL = "GET_SALARY_INCREASE_FAIL";

export const CREATE_SALARY_INCREASE = "CREATE_SALARY_INCREASE";
export const CREATE_SALARY_INCREASE_SUCCESS = "CREATE_SALARY_INCREASE_SUCCESS";
export const CREATE_SALARY_INCREASE_FAIL = "CREATE_SALARY_INCREASE_FAIL";

export const UPDATE_SALARY_INCREASE = "UPDATE_SALARY_INCREASE";
export const UPDATE_SALARY_INCREASE_SUCCESS = "UPDATE_SALARY_INCREASE_SUCCESS";
export const UPDATE_SALARY_INCREASE_FAIL = "UPDATE_SALARY_INCREASE_FAIL";

export const DELETE_SALARY_INCREASE = "DELETE_SALARY_INCREASE";
export const DELETE_SALARY_INCREASE_SUCCESS = "DELETE_SALARY_INCREASE_SUCCESS";
export const DELETE_SALARY_INCREASE_FAIL = "DELETE_SALARY_INCREASE_FAIL";
